### ISSUE TITLE
Add StockItem through API fails:null value in column part_id

### ISSUE THREAD

**Issue by rco3** [inventree/inventree-python#36]
I have successfully created new Parts via API. 

I cannot create new StockItems via API.

Tried via command-line Python code, tried via /api-doc/.  In both cases, new StockItem fails to be created (apparently) because  there is no Part being referenced:

```
item = StockItem.create(api, {
        'pk': 999,
        'part_id': 25,
        'quantity': 125,
        'notes': 'gift from Rick Cliff',
        'status': 10,
        'location': 10  # PK of a StockLocation already in the database...
    })
ERROR:root:POST request failed at 'http://192.168.1.173/api/stock/' - 500
ERROR:root:IntegrityError at /api/stock/
null value in column "part_id" violates not-null constraint
DETAIL:  Failing row contains (26, null, , null, 125.00000, 2020-08-30, null, f, t, 10, gift from Rick Cliff, f, null, null, null, null, null, null, null, 0, 1, null, 2, 13, , null, null, null).
```
Here I have referenced a valid Part (pk=25), but that reference does not appear to be passed along to create the new StockItem.  There is no field for Part in the API-DOC web interface.

**Comment by eeintech** [comment]
@rco3 Have you tried `'part'` instead of `'part_id'`?

The base part id does seem to be missing the API parameters list.

**Comment by rco3** [comment]
I have.  I have tried as both part, part-id, part_id... open to suggestion.

As the behavior is common to the /api-doc/ interface and the python wrapper for same, I'm thinking this has nothing to do with Inventree-Python.

**Comment by SchrodingersGat** [comment]
Is this fixed now that you have updated the inventree-python library?

**Comment by rco3** [comment]
I regret that it is not. 

You correctly surmised that it was the cause of the 'pk' issue, but it did not solve this issue.  I opened this in Inventree-Python because that was where I found it, but now that I see that I have the same failure when attempting to add a StockItem through the /api-doc/ interface that would appear not to be the case.
<img width="977" alt="image" src="https://user-images.githubusercontent.com/63524655/91674961-b8263980-eb08-11ea-8180-49163a279b32.png">
<img width="977" alt="image" src="https://user-images.githubusercontent.com/63524655/91674982-c83e1900-eb08-11ea-875c-3d45135393c0.png">

This installation of Inventree was updated today.  Kudos, btw - the transition to 'invoke' from 'make' went seamlessly. I'm all over that StockItem Label Template action, too. Well done, sir.

**Comment by SchrodingersGat** [comment]
Ah, found the problem. Some of the fields were set to `read_only` (in a different part of the API). And they were not being tested by the unit testing framework! Once that's merged it should be good to go.

**Comment by SchrodingersGat** [comment]
> I'm all over that StockItem Label Template action, too. Well done, sir.

Awesome! I didn't know if anyone else would manage to find it useful, but I'm glad you are! Do you have any examples of how you are using it? :)

**Comment by rco3** [comment]
Ah, you found it!  I am so relieved - easy problem, and this time it wasn't me.  

Yes, I have a sample of code suitable for a Dymo LabelWriter 450 using 4" x 2.25" (I think) labels.  And some quick start tips for others starting to develop these labels from scratch as I did,  tips on using other size labels, etc.  blabel assumes the use of separate .css which I don't see as necessary here, but the ability for Inventree to associate an image file with a given label template might be nice (company logo)

I don't have really any idea where to start integrating this workflow into Inventree, but I feel that I'm a few hours of code away from scanning a DK or Mouser barcode and having new StockItems and/or Parts added as a result using external Python code and API calls.  That code will use blabel and the same templates to generate the labels at the time the parts are added, I'm learning an awful lot here. Thanks.
